# circleci.yml file

version: 2.1

orbs:
  node: circleci/node@5.1.0
  aws-cli: circleci/aws-cli@4.1.1

jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - run:
          name: List files
          command: |
            ls -la
  #      - run:
  #          name: Build client
  #          command: |
  #            npm run build
  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - run:
          name: Deploy client
          command: |
            aws s3 cp --recursive --acl public-read ./dist s3://shopping-cli-029828047956/

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
