version: 2.1

orbs:
  node: circleci/node@5.1.0
  aws-cli: circleci/aws-cli@4.1.1

jobs:
  build_dev:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - run:
          name: Echo job name
          command: echo "build_dev"
      - run:
          name: Install Angular CLI
          command: npm install -g @angular/cli
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build client
          command: npm run build
  deploy_dev:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - aws-cli/install
      - checkout
      - run:
          name: Echo job name
          command: echo "deploy_dev"
      - run:
          name: Deploy client
          command: aws s3 cp --recursive --acl public-read ./dist/product-store s3://shopping-cli-029828047956/
  build_prod:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - run:
          name: Echo job name
          command: echo "build_prod"
      - run:
          name: Install Angular CLI
          command: npm install -g @angular/cli
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build client
          command: npm run build -- --configuration production
  deploy_prod:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - aws-cli/install
      - checkout
      - run:
          name: Echo job name
          command: echo "deploy_prod"
      - run:
          name: Deploy client
          command: aws s3 cp --recursive --acl public-read ./dist/product-store s3://shopping-cli-prod-029828047956/

workflows:
  build_and_deploy:
    jobs:
      - build_dev:
          filters:
            branches:
              only: dev
      - deploy_dev:
          requires:
            - build_dev
          filters:
            branches:
              only: dev
      - build_prod:
          filters:
            branches:
              only: master
      - deploy_prod:
          requires:
            - build_prod
          filters:
            branches:
              only: master
