version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - run:
          name: Build client
          command: |
            npm run build
  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - run:
          name: List files
          command: |
            sl -la
#       - run:
#          name: Deploy client
#          command: |
#            ./bin/deploy.sh

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
